#!/bin/sh
scriptname=$(readlink -f $0)
mypath=$(dirname $scriptname)
. "${mypath}/config.sh"
[ -z "$idoit_url" ] && idoit_url="https://localhost/"
[ -z "$zabbix_category" ] && echo "please specify zabbix_category" && exit 1
[ -z "$trigger_id_name" ] && echo "please specify trigger_id_name" && exit 1
[ -z "$trigger_name_name" ] && echo "please specify trigger_name_name" && exit 1
[ -z "$trigger_date_name" ] && echo "please specify trigger_date_name" && exit 1

object_id=$1
zabbix_status=$2
trigger_id=$3
trigger_name=$4

#The host has no object id configured
[ -z "$object_id" ] && exit 0

date=$(date)

idoit_request() {
 method=$1
 category=$2
 payload=$3

 params="{\"apikey\":\"${api_key}\",\"objID\":${object_id},\"category\":\"${category}\""
 if [ -n "$payload" ]; then
  params="${params},${payload}"
 fi 
 params="${params}}"
 data="{\"version\":\"2.0\",\"method\":\"${method}\",\"params\":${params},\"id\":10}"

 curl -s -H "Content-Type: application/json" -X POST --data "${data}" "${idoit_url}/src/jsonrpc.php"  
}

#echo "test" > /tmp/run
#echo "$1" > /tmp/to.debug
#echo "$2" > /tmp/subject.debug
#echo "$3" > /tmp/body.debug

#i-doit status:
#7: defect
#6: in operation

current_triggers=$(idoit_request "cmdb.category.read" "$zabbix_category")

case $zabbix_status in
OK)
  #only try to delete if present
  if echo $current_triggers | grep "\"${trigger_id_name}\":\"${trigger_id}\"" >/dev/null; then 
    id=$(echo $current_triggers |sed -rne "s/.+id\":\"([0-9]+).*\"${trigger_id_name}\":\"${trigger_id}\".*/\1/gp")
    idoit_request "cmdb.category.delete" "$zabbix_category" "\"id\":${id}" > /dev/null
  fi
  ;;
*)  #only add if not already added
  if echo $current_triggers | grep -v "\"${trigger_id_name}\":\"${trigger_id}\"" >/dev/null; then 
    idoit_request "cmdb.category.create" "$zabbix_category" "\"data\":{\"category_id\":1,\"${trigger_name_name}\":\"${trigger_name}\",\"${trigger_id_name}\":\"${trigger_id}\",\"${trigger_date_name}\":\"${date}\"}" > /dev/null
  fi
  ;;
esac

current_triggers=$(idoit_request "cmdb.category.read" "$zabbix_category")

if echo $current_triggers | grep '\[\]' >/dev/null; then
  new_status="6"
else
  new_status="7"
fi

idoit_request "cmdb.category.update" "C__CATG__GLOBAL" "\"data\":{\"cmdb_status\":\"${new_status}\"}" > /dev/null
